version: 0.2

phases:
  install:
    on-failure: ABORT
    commands:
      - ash -c "$(curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/master/install)"
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo $CODEBUILD_ACCOUNT_ID
      - echo $CODEBUILD_GIT_AUTHOR
      - echo $CODEBUILD_GIT_AUTHOR_EMAIL
      - echo $CODEBUILD_GIT_BRANCH
      - echo $CODEBUILD_GIT_CLEAN_BRANCH
      - echo $CODEBUILD_GIT_ESCAPED_BRANCH
      - echo $CODEBUILD_GIT_COMMIT
      - echo $CODEBUILD_GIT_SHORT_COMMIT
      - echo $CODEBUILD_GIT_MESSAGE
      - echo $CODEBUILD_GIT_TAG
      - echo $CODEBUILD_GIT_MOST_RECENT_TAG
      - echo $CODEBUILD_PROJECT
      - echo $CODEBUILD_PULL_REQUEST
      - echo `$(CODEBUILD_BUILD_NUMBER)`
      - docker build -t $IMAGE_REPO_NAME:`${CODEBUILD_GIT_BRANCH}-${CODEBUILD_BUILD_NUMBER}` .
      - docker tag $IMAGE_REPO_NAME:`${CODEBUILD_GIT_BRANCH}-${CODEBUILD_BUILD_NUMBER}` $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:`${CODEBUILD_GIT_BRANCH}-${CODEBUILD_BUILD_NUMBER}`      
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:`${CODEBUILD_GIT_BRANCH}-${CODEBUILD_BUILD_NUMBER}`