version: 0.2

phases:
  install:
    on-failure: ABORT
    commanfs:
      - ash -c "$(curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/master/install)"
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo $CODEBUILD_GIT_BRANCH
      - echo $CODEBUILD_BUILD_NUMBER
      - echo `${CODEBUILD_BUILD_NUMBER}`
      - docker build -t $IMAGE_REPO_NAME:`${CODEBUILD_GIT_BRANCH}-${CODEBUILD_BUILD_NUMBER}` .
      - docker tag $IMAGE_REPO_NAME:`${CODEBUILD_GIT_BRANCH}-${CODEBUILD_BUILD_NUMBER}` $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:`${CODEBUILD_GIT_BRANCH}-${CODEBUILD_BUILD_NUMBER}`      
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:`${CODEBUILD_GIT_BRANCH}-${CODEBUILD_BUILD_NUMBER}`